name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
    branches:
      deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Start HTTP server
      run: |
        python -m http.server 8000 &
        sleep 10

    - name: Check the server
      run: curl -I localhost:8000    
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.11.7'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
  