name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
    branches:
      deploy
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run pytest
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest
